// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CoinMarketCap Rest
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.1
 */

package cmcrest


import (
	"time"
)



type GetRateResponse struct {

	Rate float64 `json:"rate,omitempty"`

	Change24h float64 `json:"change24h,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	ErrorCode int32 `json:"error_code,omitempty"`

	ErrorMessage string `json:"error_message,omitempty"`
}

// AssertGetRateResponseRequired checks if the required fields are not zero-ed
func AssertGetRateResponseRequired(obj GetRateResponse) error {
	return nil
}

// AssertGetRateResponseConstraints checks if the values respects the defined constraints
func AssertGetRateResponseConstraints(obj GetRateResponse) error {
	return nil
}
