openapi: 3.0.3
info:
  title: CoinMarketCap Rest
  version: 1.0.0
  # 1.0.0: Create
paths:
  /v1/rate/{currency}/{fiat}:
    get:
      summary: Get crypto to fiat rate
      parameters:
        - name: currency
          in: path
          required: true
          schema:
            type: string
        - name: fiat
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Rate response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRateResponse"
components:
  schemas:
    GetRateResponse:
      type: object
      properties:
        rate:
          type: number
          format: double
        updated_at:
          type: string
          format: date-time
        error_code:
          type: integer
        error_message:
          type: string
